version: "3"

networks:
  frontend:
    external: true

services:
  heimdall:
    image: linuxserver/heimdall:2.5.6
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
    volumes:
      - ./config:/config
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`dashboard.lucascott.com`)"
      - "traefik.http.routers.heimdall.entrypoints=websecure"
      - "traefik.http.routers.heimdall.tls=true"
      - "traefik.http.routers.heimdall.tls.certresolver=letsencrypt"
      - "traefik.http.routers.heimdall.middlewares=auth@file"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"
