networks:
  reverse-proxy: { external: true }
  prometheus: { external: true }

services:
  waves-server:
    image: ghcr.io/lucascott/waves:main
    restart: unless-stopped
    volumes:
      - ./recordings:/app/static/recordings:ro
    env_file:
      - .env
    networks:
      - reverse-proxy
      - prometheus
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`mixes.lucascott.com`) && !PathPrefix(`/metrics`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt-dns
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.domains[0].sans=*.lucascott.com

  waves-audiowaveform:
    image: ghcr.io/lucascott/waves-audiowaveform:main
    restart: unless-stopped
    volumes:
      - ./recordings:/monitor
