version: "3"
networks:
  frontend:
    external: true

services:
  prometheus:
    image: prom/prometheus:v2.39.1
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data:/prometheus:rw
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.route-prefix=/
    networks:
      - frontend  
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.lucascott.com`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=letsencrypt"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.middlewares=add-trailing-slash@file"
