networks:
  reverse-proxy: { external: true }

secrets:
  CLOUDFLARE_DNS_API_TOKEN:
    file: CLOUDFLARE_DNS_API_TOKEN.secret

services:
  traefik:
    image: traefik:3
    restart: unless-stopped
    secrets:
      - CLOUDFLARE_DNS_API_TOKEN
    environment:
      CLOUDFLARE_DNS_API_TOKEN_FILE: /run/secrets/CLOUDFLARE_DNS_API_TOKEN
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yaml:/etc/traefik/traefik.yaml:ro"
      - "./traefik_dynamic.yaml:/etc/traefik/traefik_dynamic.yaml:ro"
      - "./certs:/etc/certs"
    networks:
      - reverse-proxy
    labels:
      - wud.watch.digest=true
      - wud.tag.exclude=^.*$
      - wud.link.template=https://github.com/traefik/traefik/releases
