global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: reverse-proxy
  file:
    filename: /etc/traefik/traefik_dynamic.yaml
    watch: true

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

accessLog: {}

certificatesResolvers:
  letsencrypt:
    acme:
      email: "luca@lucascott.com"
      storage: "/etc/certs/acme-http.json"
      httpChallenge:
        entryPoint: web
      # CA server to use.
      # Uncomment the line to use Let's Encrypt's staging server,
      # leave commented to go to prod.
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"

  letsencrypt-dns:
    acme:
      email: "luca@lucascott.com"
      storage: "/etc/certs/acme-dns.json"
      dnsChallenge:
        provider: cloudflare
        resolvers: ["1.1.1.1:53", "8.8.8.8:53"]

metrics:
  prometheus: {}
