networks:
  reverse-proxy:
    external: true
  prometheus:
    external: true

services:
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: 1000:1001
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
      - ./data:/var/lib/grafana
    networks:
      - reverse-proxy
      - prometheus
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.lucascott.com`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt-dns
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.domains[0].sans=*.lucascott.com
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=internalOnly@file
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000
      - wud.link.template=https://github.com/grafana/grafana/releases
