networks:
  reverse-proxy: { external: true }

services:
  grafana:
    image: grafana/grafana-oss:8.3.4
    restart: unless-stopped
    environment:
      - "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
      - ./data:/var/lib/grafana:rw
    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.lucascott.com`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt-dns"
      - "traefik.http.routers.grafana.tls.domains[0].sans=*.lucascott.com"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
