networks:
  reverse-proxy: { external: true }

volumes:
  data:

services:
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: unless-stopped
    env_file: AGENT_SECRET.secret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.lucascott.com`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt-dns"
      - "traefik.http.routers.portainer.tls.domains[0].sans=*.lucascott.com"
      - "traefik.http.routers.portainer.middlewares=internalOnly@file"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
