networks:
  reverse-proxy: { external: true }

services:
  portainer:
    image: portainer/portainer-ce:2.19.4-alpine
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.lucascott.com`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt-dns"
      - "traefik.http.routers.portainer.tls.domains[0].sans=*.lucascott.com"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
