esphome:
  name: bedroom

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

web_server:
  version: 3

prometheus:

status_led:
  pin: GPIO2

i2c:
  sda: 21
  scl: 22
  scan: true

sensor:
  - platform: bme280_i2c
    update_interval: 10s
    address: 0x76
    temperature:
      name: "BME280 Temperature"
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:
